name: Push

on:
  push:
    branches:
      - main

jobs:
  coverage:
    name: Coverage
    runs-on: ubuntu-latest
    steps:
      - name: checkout main branch
        uses: actions/checkout@v3

      - uses: actions/setup-go@v3
        with:
          go-version: 1.19

      - run: go test -coverprofile=cover.out . transport/...

      - name: checkout covrage branch
        uses: actions/checkout@v3
        with:
          ref: 'coverage'
          path: coverage

      - run: go tool cover -html=cover.out -o coverage/coverage.html

      - name: commit coverage output
        working-directory: coverage
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add .
          git commit -m "update coverage"

      - uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          directory: coverage
          branch: coverage